volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  nuclei_backend:
    # image: ronnytec/nuclei:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
        - 8000:8000
    user: root
    privileged: true

    
  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
  # ipfs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.kubo
  #   restart: unless-stopped
  #   ports:
  #     - 4001:4001/tcp
  #     - 4001:4001/udp
      
  #     # The following ports only listen on the loopback interface, so are not remotely reachable by default.
  #     # If you want to override these or add more ports, see https://docs.docker.com/compose/extends/ .
      
  #     # API port, which includes admin operations, so you probably don't want this remotely accessible.
  #     - 127.0.0.1:5001:5001
      
  #     # HTTP Gateway
  #     - 127.0.0.1:8080:8080
  ipfs:
    image: ipfs/go-ipfs:latest
    command: 
      - daemon 
      - --migrate=true 
      - --mount
      - --routing=dhtclient
      - --enable-namesys-pubsub
    privileged: true    # not needed in theory, adding this makes no difference though
    cap_add:
        - SYS_ADMIN
    security_opt:
        - apparmor:unconfined
    devices:
        - /dev/fuse:/dev/fuse
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    ports:
        - 8080:8080   # public gateway
        - 4001:4001   # public swarm UDP
        - 5001:5001   # private API
    volumes:
        - ./data/ipfs:/ipfsdata
        - /etc/fuse.conf:/etc/fuse.conf:ro
        - ./data/ipfs:/data/ipfs
        - ./data/export:/export