version: '3'

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379

  ipfs:
    image: ipfs/go-ipfs:latest
    command: 
      - daemon 
      - --migrate=true 
      - --mount
      - --routing=dhtclient
      - --enable-namesys-pubsub
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - ./data/ipfs:/ipfsdata
      - /etc/fuse.conf:/etc/fuse.conf:ro
      - ./data/ipfs:/data/ipfs
      - ./data/export:/export

  traefik:
    image: traefik:v2.5
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=Rohaanerodasahmed@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    restart: unless-stopped

  nuclei_backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuclei-backend.rule=Host(`nucleibackend.systems`)"
      - "traefik.http.routers.nuclei-backend.entrypoints=websecure"
      - "traefik.http.routers.nuclei-backend.tls.certresolver=myresolver"
      - "traefik.http.routers.nuclei-backend.tls=true"

    expose:
      - 8000
    ports:
      - 8000:8000

    environment:
      - "DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432/postgres"
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - data:/app/data
